package org.barahi.server.serializer;

import org.barahi.server.json.LobbyJson;
import org.barahi.serviceapi.lobby.Lobby;
import org.barahi.serviceapi.lobby.LobbyImpl;

public class LobbySerializer {
    public LobbyJson toJson(Lobby lobby) {
        LobbyJson json = new LobbyJson();
        json.setId(lobby.getId());
        json.setGameSettingsId(lobby.getGameSettingsId());
        json.setPlayerIds(lobby.getPlayerIds());
        json.setGameStarted(lobby.isGameStarted());
        return json;
    }

    public Lobby fromJson(LobbyJson json) {
        return new LobbyImpl(
            null,  // id will be generated by Service
            json.getGameSettingsId(),
            json.getPlayerIds() != null ? json.getPlayerIds() : new String[]{},
            json.isGameStarted()
        );
    }
}