ALTER TABLE game_state
DROP CONSTRAINT IF EXISTS CONSTRAINT_GAME_STATE_GAME_PHASE_ID;

ALTER TABLE `game_state`
DROP COLUMN game_phase_id;

ALTER TABLE `game_state`
ADD COLUMN phase VARCHAR(50);

DROP TABLE `game_state_phases`;



